version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}				
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5434:${POSTGRES_PORT}
    volumes:
      - postgresvol:/var/lib/docker/volumes/postgresvol/_data
    networks:
      - metapost
  
  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin
    hostname: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadminvol:/var/lib/docker/volumes/pgadminvol/_data
    networks:
      - metapost

volumes:
  postgresvol:
  pgadminvol:

networks:
  metapost:
    driver: bridge
