"""Add CASCADE on delete for user_id in transaction_categories, financial_groups, bank_cards tables.

Revision ID: 20c974f80d26
Revises: f926a7487f33
Create Date: 2025-05-26 11:55:13.136070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c974f80d26'
down_revision: Union[str, None] = 'f926a7487f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bank_cards_user_id_fkey'), 'bank_cards', type_='foreignkey')
    op.create_foreign_key('bank_cards_user_id_fkey', 'bank_cards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('financial_groups_user_id_fkey'), 'financial_groups', type_='foreignkey')
    op.create_foreign_key('financial_groups_user_id_fkey', 'financial_groups', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('transaction_categories_user_id_fkey'), 'transaction_categories', type_='foreignkey')
    op.create_foreign_key('transaction_categories_user_id_fkey', 'transaction_categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_categories_user_id_fkey', 'transaction_categories', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_categories_user_id_fkey'), 'transaction_categories', 'users', ['user_id'], ['id'])
    op.drop_constraint('financial_groups_user_id_fkey', 'financial_groups', type_='foreignkey')
    op.create_foreign_key(op.f('financial_groups_user_id_fkey'), 'financial_groups', 'users', ['user_id'], ['id'])
    op.drop_constraint('bank_cards_user_id_fkey', 'bank_cards', type_='foreignkey')
    op.create_foreign_key(op.f('bank_cards_user_id_fkey'), 'bank_cards', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
