"""Add SET NULL on delete for transaction.category_id (if category is deleted, transaction should not be deleted)

Revision ID: 56aed9cc3a24
Revises: 9c547261432a
Create Date: 2025-05-25 20:52:30.565121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56aed9cc3a24'
down_revision: Union[str, None] = '9c547261432a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transactions_category_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_category_id_fkey', 'transactions', 'transaction_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_category_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_category_id_fkey'), 'transactions', 'transaction_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
