"""Add users.id for financial_groups & transaction_categories

Revision ID: 9c547261432a
Revises: 6fdd935402be
Create Date: 2025-05-25 16:34:47.487604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c547261432a'
down_revision: Union[str, None] = '6fdd935402be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_groups', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('financial_groups_user_id_fkey', 'financial_groups', 'users', ['user_id'], ['id'])
    op.add_column('transaction_categories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('transaction_categories_user_id_fkey', 'transaction_categories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_categories_user_id_fkey', 'transaction_categories', type_='foreignkey')
    op.drop_column('transaction_categories', 'user_id')
    op.drop_constraint('financial_groups_user_id_fkey', 'financial_groups', type_='foreignkey')
    op.drop_column('financial_groups', 'user_id')
    # ### end Alembic commands ###
