"""Add CASCADE on delete for transaction.bank_card_id and transaction.financial_group_id

Revision ID: f926a7487f33
Revises: 56aed9cc3a24
Create Date: 2025-05-25 21:00:21.716594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f926a7487f33'
down_revision: Union[str, None] = '56aed9cc3a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transactions_bank_card_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_financial_group_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_financial_group_id_fkey', 'transactions', 'financial_groups', ['financial_group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('transactions_bank_card_id_fkey', 'transactions', 'bank_cards', ['bank_card_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transactions_financial_group_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_bank_card_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_financial_group_id_fkey'), 'transactions', 'financial_groups', ['financial_group_id'], ['id'])
    op.create_foreign_key(op.f('transactions_bank_card_id_fkey'), 'transactions', 'bank_cards', ['bank_card_id'], ['id'])
    # ### end Alembic commands ###
